project:
  type: website
  preview:
    port: 3434
    browser: true
execute:
  freeze: auto
website:
  title: "Data and Tech Handbook"
  announcement:
    dismissable: false
    content: "**Welcome!** - This site is an early draft and prototype. Content, pages, and the site are subject to change."
    position: above-navbar
    type: warning
    icon: cone-striped
  description:  "Research, Software, and Data Resources from Innovations for Poverty Action."
  favicon: ./assets/images/IPA-primary-full-color-abbreviated.png
  # site-url: https://research.poverty-action.org
  repo-url: https://github.com/PovertyAction/research-resources
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  reader-mode: false
  search:
    show-item-context: true
    location: sidebar
    type: textbox
    limit: 20
  page-footer:
    left: |
      Brought to you by
      [![](../../assets/images/IPA-primary-color-RGB.png){fig-alt="IPA" width=65px}](https://poverty-action.org)
    # center:
    #   - text: "About"
    #     href: about.qmd
    #   - text: "FAQ"
    #     href: docs/faq/index.qmd
    #   - text: "License"
    #     href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com/poverty_action
        aria-label: IPA Twitter
      - icon: github
        href: https://github.com/PovertyAction/ipa-data-tech-handbook
        aria-label: IPA GitHub
      # - icon: rss
        # href: https://povertyaction.github.io/research/blog/index.xml
        # aria-label: IPA Data Research Blog RSS
  navbar:
    background: '#155240'
    foreground: '#ffffff'
    logo: ./assets/images/IPA-primary-white-abbreviated.png
    # logo: quarto.png
    # logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: docs/about/index.qmd
      # - text: "Guides"
      #   href: docs/guides/index.qmd
      - text: "Software Guides"
        href: docs/software/index.qmd
      # - text: "Methods"
      #   href: docs/methods/index.qmd
      - text: "Research Design"
        href: docs/research_design/index.qmd
      - text: "Ethics & Data Security"
        href: docs/ethics_&_data_security/index.qmd
      - text: "Measurement & Survey Design"
        href: docs/measurement_&_survey_design/index.qmd
      - text: "Data Collection Methods"
        href: docs/data_collection_methods/index.qmd
      - text: "Data Management"
        href: docs/data_management/index.qmd
      - text: "Publication & Policy"
        href: docs/publication_&_policy/index.qmd
      
    right:
      - text: "IPA Teams"
        menu:
          - href: docs/teams/dse.qmd
            text: DSE
          - href: docs/teams/grds.qmd
            text: GRDS
          - href: docs/teams/mist.qmd
            text: MIST
          - href: docs/teams/ppi.qmd
            text: PPI

      - text: "Contributing"
        href: ./contributing.qmd
      - icon: github
        href: https://github.com/PovertyAction/ipa-data-tech-handbook
        aria-label: IPA GitHub

  sidebar:
    # background: '#155240'
    # foreground: '#ffffff'

    - id: about
      style: "floating"
      collapse-level: 2
      align: left

      contents:
        - section: "About"
          href: docs/about/index.qmd
          contents:
          - text: "Foundations"
            href: docs/about/foundations.qmd
          - text: "Minimum Must Dos"
            href: docs/about/mmds.qmd
          - text: "For IPA Researchers"
            href: docs/about/ipa_researchers.qmd
          - text: "For IPA staff"
            href: docs/about/ipa_staff.qmd


    - id: guides
      collapse-level: 1
      contents:
        - section: "Guides"
          href: docs/guides/index.qmd
          contents:
            - text: "Coding Best Practices"
              href: docs/guides/coding_best_practices.qmd
            - text: "Code Review"
              href: docs/guides/code_review.qmd

    - id: software
      collapse-level: 3
      contents:
        - section: "Software"
          href: docs/software/index.qmd
          contents:
            - section: "Programming"
              contents:
                - text: "Python"
                  href: docs/software/python.qmd
                - text: "Stata"
                  href: docs/software/stata.qmd
                - text: "SQL"
                  href: docs/software/sql.qmd

            - section: "Data Collection"
              contents:
                - section: "SurveyCTO"
                  contents:
                    - text: "About SurveyCTO"
                      href: docs/software/surveycto/index.md
                    - text: "SurveyCTO: Best Practices"
                      href: docs/software/surveycto/scto_best_practices.qmd
                    - text: "SurveyCTO: IPA Tools"
                      href: docs/software/surveycto/scto_tools.qmd

            - section: Tools
              contents:
                - text: "Computer Setup"
                  href: docs/software/computer_setup.qmd
                - text: "Virtual Environments"
                  href: docs/software/venv.qmd
                - text: "Git"
                  href: docs/software/git.qmd
                - text: "GitHub"
                  href: docs/software/github.qmd
                - text: "VS Code"
                  href: docs/software/vscode.qmd
                - text: "Quarto"
                  href: docs/software/quarto.qmd
                - text: "Just"
                  href: docs/software/justfile.qmd
                - text: "Pre-commit"
                  href: docs/software/pre_commit_hooks.qmd

    - id: methods
      collapse-level: 2
      contents:
        - section: "Methods"
          href: docs/methods/index.qmd
          contents:
            - text: "Machine Learning"
              href: docs/methods/ml.qmd
            - text: "References"
              href: docs/methods/references.qmd

    - id: data_collection_methods
      collapse-level: 3
      contents:
        - section: "Data Collection Methods"
          href: docs/data_collection_methods/index.qmd
          contents:
            - section: "WhatsApp Surveys"
              href: docs/data_collection_methods/whatsapp_surveys/index.qmd
              contents:
                - text: "Getting Started With WhatsApp Surveys"
                  href: docs/data_collection_methods/whatsapp_surveys/getting_started_with_whatsapp_surveys.qmd
                - text: "The Twilio Console"
                  href: docs/data_collection_methods/whatsapp_surveys/the_twilio_console.qmd
                - text: "How To Program A WhatsApp Survey"
                  href: docs/data_collection_methods/whatsapp_surveys/how_to_program_a_whatsapp_survey.qmd
                - text: "Launching A WhatsApp Survey"
                  href: docs/data_collection_methods/whatsapp_surveys/launching_a_whatsapp_survey.qmd
                - text: "Encryption And Data Security In WhatsApp Surveys"
                  href: docs/data_collection_methods/whatsapp_surveys/encryption_and_data_security_in_whatsapp_surveys.qmd
            
            - section: "Qualitate Research"
              href: docs/data_collection_methods/qualitative_research/index.qmd
              contents:
                - text: "Introduction"
                  href: docs/data_collection_methods/qualitative_research/introduction.qmd
                
                - section: "Best Practices Guides"
                  href: docs/data_collection_methods/qualitative_research/best_practices_guides/index.qmd
                  contents:
                    - text: "Focus Groups"
                      href: docs/data_collection_methods/qualitative_research/best_practices_guides/focus_groups.qmd
                    - text: "Interviews"
                      href: docs/data_collection_methods/qualitative_research/best_practices_guides/interviews.qmd
                    - text: "Observations"
                      href: docs/data_collection_methods/qualitative_research/best_practices_guides/observations.qmd
                    - text: "Rapid Ethnographies"
                      href: docs/data_collection_methods/qualitative_research/best_practices_guides/rapid_ethnographies.qmd






    - id: data_management
      collapse-level: 2
      contents:
        - section: "Data Management"
          href: docs/data_management/index.qmd
    
    - id: ethics_&_data_security
      collapse-level: 2
      contents:
        - section: "Ethics & Data Security"
          href: docs/ethics_&_data_security/index.qmd

    - id: measurement_&_survey_design
      collapse-level: 2
      contents:
        - section: "Measurement & Survey Design"
          href: docs/measurement_&_survey_design/index.qmd
      
    - id: research_design
      collapse-level: 2
      contents:
        - section: "Research Design"
          href: docs/research_design/index.qmd

    - id: publication_&_policy
      collapse-level: 2
      contents:
        - section: "Publication & Policy"
          href: docs/publication_&_policy/index.qmd

# bibliography: ./assets/references.bib

format:
  html:
    output-ext: html
    template-partials:
      - ./assets/title-block.html
      - ./assets/toc.html
    title-block-banner: false
    theme:
      light: [cosmo, ./assets/theme.scss]
    toc: true
    code-background: true
    code-copy: true
    code-overflow: wrap
    css: ./assets/styles.css
    include-after-body: ./assets/js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
